LOG_LEVEL: debug
CA_ROOT: /home/cosmin/projects/device-worker-ng/resources/certificates/ca.pem
CERT: /home/cosmin/projects/device-worker-ng/resources/certificates/cert.pem
KEY: /home/cosmin/projects/device-worker-ng/resources/certificates/key.pem
SERVER: 127.0.0.1:8080
XDG_RUNTIME_DIR: /run/user/1000
KUBECONFIG: /home/cosmin/.kube/minikube.yaml
DEVICE_ID: toto
